docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown.
time="2019-11-05T13:17:34-05:00" level=error msg="error waiting for container: context canceled"
